//! The shared vocabulary an effect site is described in: the funnel groups,
//! the resource-ledger rows, the durable events and adjacency, the fault-matrix
//! rows, the scopes, the injection modes and hosts, and the parent-side
//! sub-effect points.
//!
//! Split out of `topology::effects`; the parent re-exports every item here, so
//! `crate::topology::effects::FunnelGroup` and its siblings are unchanged
//! paths.

use std::fmt;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Vocabulary
// ---------------------------------------------------------------------------

/// The eleven funnel API groups (`decisions.effect_site_inventory.identity`).
///
/// A group is an API surface, not a resource: one group can span several
/// [`ResourceRow`]s, and one row can be reached from several groups. The
/// grouping is what makes `hook(Before, site) -> primitive -> hook(After, site)`
/// implementable once per funnel rather than once per site.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FunnelGroup {
    Worktree,
    Snapshot,
    Ref,
    Object,
    RunDir,
    Event,
    Answer,
    Lock,
    Report,
    Process,
    Container,
}

impl FunnelGroup {
    /// Every group, in the order `identity` names them.
    pub const ALL: &'static [Self] = &[
        Self::Worktree,
        Self::Snapshot,
        Self::Ref,
        Self::Object,
        Self::RunDir,
        Self::Event,
        Self::Answer,
        Self::Lock,
        Self::Report,
        Self::Process,
        Self::Container,
    ];

    /// The group's name as it appears in a site's dotted name.
    pub const fn name(self) -> &'static str {
        match self {
            Self::Worktree => "Worktree",
            Self::Snapshot => "Snapshot",
            Self::Ref => "Ref",
            Self::Object => "Object",
            Self::RunDir => "RunDir",
            Self::Event => "Event",
            Self::Answer => "Answer",
            Self::Lock => "Lock",
            Self::Report => "Report",
            Self::Process => "Process",
            Self::Container => "Container",
        }
    }

    /// The funnel module this group's effects are confined to
    /// (`decisions.effect_site_inventory.mechanism`, the funnel-module list).
    ///
    /// Recorded per group rather than per site because the allow-placement scan
    /// PR6 builds works on modules: a module either performs effects only
    /// inside site-taking APIs, or it does not.
    ///
    /// This is the inventory's *declared* module, which is the packet's answer
    /// and is not everywhere the funnel body sits today. The answer funnels are
    /// declared in `src/interaction.rs`, and `interaction::write_question`,
    /// `write_answer` and `read_answer` are delegations to bodies in
    /// `src/rundir.rs`. Both files are allowlisted funnel modules, so
    /// enforcement is unchanged either way; the disagreement is checked in, per
    /// site, as `effects/funnel-modules.json`, generated by
    /// `effects::tests::artifacts::funnel_module_record`. A scan built on this
    /// answer scans the declared module and not the body.
    pub const fn module(self) -> &'static str {
        match self {
            Self::Worktree | Self::Snapshot | Self::Ref | Self::Object => {
                "src/workspace_manager.rs"
            }
            Self::RunDir | Self::Lock => "src/rundir.rs",
            Self::Event => "src/events/log.rs",
            Self::Answer => "src/interaction.rs",
            Self::Report => "src/util.rs",
            Self::Process => "src/runner/host.rs",
            Self::Container => "src/runner/container.rs",
        }
    }
}

impl fmt::Display for FunnelGroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// The resource-ledger rows an effect site can touch
/// (`decisions.resource_accounting.rows`).
///
/// Two different ledger rules keep rows out of this enum. R1–R8 and R13–R16
/// are the logical fold/broker domain, which
/// `resource_accounting.enforcement_domains` says takes no effect-site mapping
/// at all — "no effect-site mapping required or allowed". R20 is
/// external-physical and is still absent: credential volumes are
/// `operator_owned`, "never created or pruned by a run"
/// (`resource_accounting.rows[R20]`, quoted at the guard in
/// `src/runner/container.rs` that refuses an invocation rather than let
/// `docker create` conjure one), so a run performs no effect on the row and no
/// site can name it. Their absence from this enum is those two rules expressed
/// as a type.
///
/// So the fifteen here are the rows a run can act on — not every
/// external-physical and process-local-OS row the ledger has. A claim
/// quantified over [`Self::ALL`] is a claim about those fifteen and about R20
/// only by way of the sentence above.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceRow {
    /// Task worktree + its durable synced intent, and the objects its index or
    /// HEAD references.
    R9,
    /// Staging worktree `merge/<seq>` + its intent (stale candidates only).
    R10,
    /// Candidates ref: authoritative candidate identity.
    R11,
    /// `prepared/<seq>` proposal pin (stale candidates only).
    R12,
    /// The coordinator's own lock holds (OS lock state only).
    R17,
    /// Execution root directory.
    R18,
    /// Disposable Git view directory (container runner).
    R19,
    /// Integration ref and run-scoped run-directory contents, public and
    /// private.
    R21,
    /// Host process handle / private job object / ambient job membership.
    R22,
    /// Candidate-prepared pin (non-authoritative).
    R23,
    /// Exact gate/review snapshot worktree + its intent.
    R24,
    /// The repository-scoped `upstroke-worktree.lock` file itself.
    R25,
    /// Container invocation: the container, its labels, and its global intent.
    R26,
    /// Engine-created Git objects no engine ref, pin, or worktree references.
    R27,
    /// A surviving Unix reaper's shared `cleanup.lock` hold -- and, since
    /// `PR8-CRASH-002` closed, the same hold by an engine `git update-ref`
    /// child for as long as it lives.
    R28,
}

impl ResourceRow {
    /// Every row an effect site may name, in ledger order.
    pub const ALL: &'static [Self] = &[
        Self::R9,
        Self::R10,
        Self::R11,
        Self::R12,
        Self::R17,
        Self::R18,
        Self::R19,
        Self::R21,
        Self::R22,
        Self::R23,
        Self::R24,
        Self::R25,
        Self::R26,
        Self::R27,
        Self::R28,
    ];

    /// The row's ledger id.
    pub const fn name(self) -> &'static str {
        match self {
            Self::R9 => "R9",
            Self::R10 => "R10",
            Self::R11 => "R11",
            Self::R12 => "R12",
            Self::R17 => "R17",
            Self::R18 => "R18",
            Self::R19 => "R19",
            Self::R21 => "R21",
            Self::R22 => "R22",
            Self::R23 => "R23",
            Self::R24 => "R24",
            Self::R25 => "R25",
            Self::R26 => "R26",
            Self::R27 => "R27",
            Self::R28 => "R28",
        }
    }

    /// Which enforcement domain the row belongs to.
    ///
    /// The distinction matters to ST-09 rather than to ST-07, but it is a
    /// property of the row and belongs beside it: a process-local row is
    /// released by the OS at process death and is never released by cleanup,
    /// so an entry that tables a cleanup step for one is wrong on its face.
    pub const fn domain(self) -> EnforcementDomain {
        match self {
            Self::R17 | Self::R22 | Self::R28 => EnforcementDomain::ProcessLocalOs,
            Self::R9
            | Self::R10
            | Self::R11
            | Self::R12
            | Self::R18
            | Self::R19
            | Self::R21
            | Self::R23
            | Self::R24
            | Self::R25
            | Self::R26
            | Self::R27 => EnforcementDomain::ExternalPhysical,
        }
    }
}

impl fmt::Display for ResourceRow {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// The two enforcement domains an effect site's row can belong to.
///
/// The logical fold/broker domain is deliberately absent: it has no sites.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EnforcementDomain {
    /// State on a real filesystem, ref store, or container runtime.
    ExternalPhysical,
    /// OS state bound to a process lifetime, released by the OS at its death.
    ProcessLocalOs,
}

/// Every tag the schema-4 vocabulary can write.
///
/// A mirror of [`crate::topology::events::TOPOLOGY_EVENT_KINDS`], typed so that
/// a site's adjacency is a value the compiler checks rather than a string a
/// typo can invent. The two lists are asserted equal element-for-element by
/// `topology::effects::tests::the_adjacency_vocabulary_is_the_logs_vocabulary`,
/// so a change to the vocabulary breaks **that assertion** rather than silently
/// leaving a site pointing at an append that no longer exists.
///
/// The guard is named rather than called "a unit test in this module" because
/// the split moved this type out of the root: "this module" now reads as
/// `vocab`, and the assertion is in a *sibling* of it. The property is
/// unchanged -- the test still fires -- but a reader who took the locality at
/// its word would be looking for the guard in the wrong place, and the danger
/// in that is removing the real one believing the documented one applies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DurableEvent {
    RunStarted,
    RunResumed,
    TaskSpawned,
    TaskDispatched,
    AttemptStarted,
    AttemptFinished,
    AttemptInterrupted,
    GenerationClosed,
    DeferWaitElapsed,
    CandidatePrepared,
    TaskCandidateCreated,
    MergeVerificationStarted,
    MergeVerificationUnavailable,
    MergeVerificationInterrupted,
    MergePrepared,
    MergeRejected,
    TaskMerged,
    QuestionRaised,
    QuestionAnswered,
    BudgetExceeded,
    RunFinished,
    CapacitySnapshot,
    PoolExhausted,
    DesignDefect,
}

impl DurableEvent {
    /// Every kind, in the vocabulary's declaration order.
    pub const ALL: &'static [Self] = &[
        Self::RunStarted,
        Self::RunResumed,
        Self::TaskSpawned,
        Self::TaskDispatched,
        Self::AttemptStarted,
        Self::AttemptFinished,
        Self::AttemptInterrupted,
        Self::GenerationClosed,
        Self::DeferWaitElapsed,
        Self::CandidatePrepared,
        Self::TaskCandidateCreated,
        Self::MergeVerificationStarted,
        Self::MergeVerificationUnavailable,
        Self::MergeVerificationInterrupted,
        Self::MergePrepared,
        Self::MergeRejected,
        Self::TaskMerged,
        Self::QuestionRaised,
        Self::QuestionAnswered,
        Self::BudgetExceeded,
        Self::RunFinished,
        Self::CapacitySnapshot,
        Self::PoolExhausted,
        Self::DesignDefect,
    ];

    /// This kind's tag, as the log writes it.
    pub const fn kind(self) -> &'static str {
        match self {
            Self::RunStarted => "run_started",
            Self::RunResumed => "run_resumed",
            Self::TaskSpawned => "task_spawned",
            Self::TaskDispatched => "task_dispatched",
            Self::AttemptStarted => "attempt_started",
            Self::AttemptFinished => "attempt_finished",
            Self::AttemptInterrupted => "attempt_interrupted",
            Self::GenerationClosed => "generation_closed",
            Self::DeferWaitElapsed => "defer_wait_elapsed",
            Self::CandidatePrepared => "candidate_prepared",
            Self::TaskCandidateCreated => "task_candidate_created",
            Self::MergeVerificationStarted => "merge_verification_started",
            Self::MergeVerificationUnavailable => "merge_verification_unavailable",
            Self::MergeVerificationInterrupted => "merge_verification_interrupted",
            Self::MergePrepared => "merge_prepared",
            Self::MergeRejected => "merge_rejected",
            Self::TaskMerged => "task_merged",
            Self::QuestionRaised => "question_raised",
            Self::QuestionAnswered => "question_answered",
            Self::BudgetExceeded => "budget_exceeded",
            Self::RunFinished => "run_finished",
            Self::CapacitySnapshot => "capacity_snapshot",
            Self::PoolExhausted => "pool_exhausted",
            Self::DesignDefect => "design_defect",
        }
    }
}

impl fmt::Display for DurableEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.kind())
    }
}

/// The durable append a site's effect is ordered against.
///
/// `Before` means the effect is designed to be durable before the append is;
/// `After` means the append is durable first. `None` is not "unknown": it is
/// the answer for a site that *is* the append (the whole [`EventSite`](crate::topology::effects::EventSite) append
/// group), and for a site that runs outside any run's log at all — the husk
/// census removes a run directory belonging to a run whose log it has refused
/// to fold.
///
/// The value decides [`EffectSiteId::observable_orders`](crate::topology::effects::EffectSiteId::observable_orders), which is what the
/// registry's order axis ranges over.
///
/// The wire form is the externally tagged enum: `{"before": "<tag>"}`,
/// `{"after": "<tag>"}`, or `"none"`. That representation is what refuses a
/// second key and an undeclared one. A `deny_unknown_fields` was carried here
/// and did nothing — a newtype or unit variant has no field to deny on —
/// measured by removing it and seeing every refusal in
/// `tests::an_adjacency_round_trips_and_refuses_a_second_key_or_an_unknown_one`
/// still hold.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Adjacent {
    /// The effect precedes this append.
    Before(DurableEvent),
    /// This append precedes the effect.
    After(DurableEvent),
    /// No append is adjacent.
    None,
}

impl Adjacent {
    /// The append this site is ordered against, where there is one.
    pub const fn event(self) -> Option<DurableEvent> {
        match self {
            Self::Before(kind) | Self::After(kind) => Some(kind),
            Self::None => None,
        }
    }
}

/// The transaction fault-matrix row a fault at a site lands in.
///
/// One variant per row of `transaction_fault_matrix`, in its order. The row is
/// what says which durable prefix the fault leaves and what a resume does about
/// it; the site says where the fault can happen.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FaultRow {
    TRunstart,
    TDispatch,
    TAttempt,
    TRetry,
    TCandObj,
    TCandRef,
    TScrub,
    TFailed,
    TRetained,
    TFast,
    TProposal,
    TVerify,
    TPrepared,
    TReject,
    TRepairDispatch,
    TContainer,
    TAppend,
    TAnswer,
    TFinish,
    TFinalize,
    TResume,
}

impl FaultRow {
    /// Every row, in matrix order.
    pub const ALL: &'static [Self] = &[
        Self::TRunstart,
        Self::TDispatch,
        Self::TAttempt,
        Self::TRetry,
        Self::TCandObj,
        Self::TCandRef,
        Self::TScrub,
        Self::TFailed,
        Self::TRetained,
        Self::TFast,
        Self::TProposal,
        Self::TVerify,
        Self::TPrepared,
        Self::TReject,
        Self::TRepairDispatch,
        Self::TContainer,
        Self::TAppend,
        Self::TAnswer,
        Self::TFinish,
        Self::TFinalize,
        Self::TResume,
    ];

    /// The row's id, exactly as the matrix writes it.
    pub const fn id(self) -> &'static str {
        match self {
            Self::TRunstart => "T-RUNSTART",
            Self::TDispatch => "T-DISPATCH",
            Self::TAttempt => "T-ATTEMPT",
            Self::TRetry => "T-RETRY",
            Self::TCandObj => "T-CAND-OBJ",
            Self::TCandRef => "T-CAND-REF",
            Self::TScrub => "T-SCRUB",
            Self::TFailed => "T-FAILED",
            Self::TRetained => "T-RETAINED",
            Self::TFast => "T-FAST",
            Self::TProposal => "T-PROPOSAL",
            Self::TVerify => "T-VERIFY",
            Self::TPrepared => "T-PREPARED",
            Self::TReject => "T-REJECT",
            Self::TRepairDispatch => "T-REPAIR-DISPATCH",
            Self::TContainer => "T-CONTAINER",
            Self::TAppend => "T-APPEND",
            Self::TAnswer => "T-ANSWER",
            Self::TFinish => "T-FINISH",
            Self::TFinalize => "T-FINALIZE",
            Self::TResume => "T-RESUME",
        }
    }
}

impl fmt::Display for FaultRow {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.id())
    }
}

/// Which claim a site is inside (`decisions.effect_site_inventory.scope`).
///
/// `Topology` and `Shared` carry the full ST-07 requirement. `Legacy` sites are
/// inventoried and row-mapped and carry no fault-registry requirement beyond
/// today's legacy tests — they exist because the Event funnel is shared and its
/// legacy callers have to pass *something*, and a scope is a safer thing for
/// them to pass than a site that also claims topology coverage.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SiteScope {
    /// Reached only by schema-4 paths.
    Topology,
    /// Reached by both schema-4 and legacy paths through one funnel.
    Shared,
    /// Reached only by schema-1..3 paths.
    Legacy,
}

impl SiteScope {
    /// Whether this scope carries the ST-07 bijection requirement.
    pub const fn is_claimed(self) -> bool {
        match self {
            Self::Topology | Self::Shared => true,
            Self::Legacy => false,
        }
    }
}

/// How a fault is introduced at a parent-side sub-effect point.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InjectionMode {
    /// The process dies at the point.
    Kill,
    /// The funnel returns `Err` from the point, after performing or partially
    /// performing the primitive.
    ErrorReturn,
}

impl InjectionMode {
    /// Both modes.
    pub const ALL: &'static [Self] = &[Self::Kill, Self::ErrorReturn];
}

/// Which host a sub-effect point exists on.
///
/// The containment steps are the only points that differ: a Windows ambient
/// job has no Unix counterpart and a Unix reaper has no Windows one. ST-07's
/// evidence "executes each point on its platform", so the bijection check is
/// told which platform it is running on and does not require a point that
/// cannot exist there.
///
/// This is a property of a *point*, not a machine: [`Self::Any`] means "exists
/// wherever the parent runs". A host is [`Host`], which has no such value —
/// see the type for why the two are not one enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    /// Present on every host.
    Any,
    /// Present only on Windows.
    Windows,
    /// Present only on Unix.
    Unix,
}

/// The host a bijection check is running on.
///
/// Two values, and deliberately not [`Platform`]'s three. `required_on` used to
/// take a `Platform` as its host and answer the `(Windows, Any)` and
/// `(Unix, Any)` pairs through a `(Self::Windows, _) | (Self::Unix, _) => false`
/// wildcard — so `Platform::Any` named a host on which *neither* platform's
/// containment points were required, and `check_bijection` returned success for
/// `Process.Spawn` with all eight containment points unobserved and unentered.
/// A checker that can be handed a host meaning "no platform" is a checker whose
/// strongest claim is optional.
///
/// The fix is the type rather than a guard: a machine is Windows or it is Unix,
/// and there is no third value to reject at a boundary, forget to reject at the
/// next one, or serialize into a registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Host {
    /// A Windows host: the ambient- and private-job containment steps exist.
    Windows,
    /// A Unix host: the reaper containment steps exist.
    Unix,
}

impl Host {
    /// Both hosts.
    ///
    /// A platform-dependent claim quantified over this slice cannot be vacuous
    /// on the host the build is not running on, which is exactly what
    /// [`Self::current`] alone cannot give: a build that only ever checks its
    /// own host cannot fail for the other one until that one's CI cell does.
    /// The self-tests that pin the platform relation itself — which points
    /// [`Platform::required_on`] requires of which host — are crossed over this
    /// slice for that reason.
    ///
    /// Not every self-test is, and the wording here used to say otherwise.
    /// Several drive `check_bijection` at [`Self::current`] and filter points
    /// by `required_on(Host::current())`, so what those establish about the
    /// other host is whatever the relation crossed over this slice establishes,
    /// and no more.
    pub const ALL: &'static [Self] = &[Self::Windows, Self::Unix];

    /// The host's name.
    pub const fn name(self) -> &'static str {
        match self {
            Self::Windows => "windows",
            Self::Unix => "unix",
        }
    }

    /// The host this build is running on.
    pub const fn current() -> Self {
        if cfg!(windows) {
            Self::Windows
        } else {
            Self::Unix
        }
    }

    /// The other host.
    pub const fn other(self) -> Self {
        match self {
            Self::Windows => Self::Unix,
            Self::Unix => Self::Windows,
        }
    }

    /// This host as a point platform: the platform whose points it requires.
    pub const fn platform(self) -> Platform {
        match self {
            Self::Windows => Platform::Windows,
            Self::Unix => Platform::Unix,
        }
    }
}

impl fmt::Display for Host {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl Platform {
    /// Whether a point declared for `self` has to be observed on `host`.
    ///
    /// Every pair is written out. No wildcard stands in for the two negative
    /// answers, so a host value added later fails to compile here instead of
    /// quietly joining the `false` arm and excusing a platform's points from
    /// the bijection.
    pub const fn required_on(self, host: Host) -> bool {
        match (self, host) {
            (Self::Any, Host::Windows) | (Self::Any, Host::Unix) => true,
            (Self::Windows, Host::Windows) | (Self::Unix, Host::Unix) => true,
            (Self::Windows, Host::Unix) | (Self::Unix, Host::Windows) => false,
        }
    }
}

/// A parent-side point inside a funnel, between two steps of one logical
/// effect.
///
/// A hook is parent-executed code and can be executed only where the parent
/// runs. These are the places inside a funnel where that is still true: after
/// a child has exited but before the parent recorded what it printed
/// ([`Self::IdUnread`]), between a write and its sync ([`Self::Written`],
/// [`Self::Synced`]), inside the log-open sequence, and at the containment
/// steps of a spawn — which are parent-side or, for
/// [`Self::PreExecPgidAndRegister`], run in the forked child before `exec`,
/// which is still this crate's code and still under the harness's control.
///
/// Everything that is *not* on this list and not a hook phase is a command-
/// internal residue class instead. The distinction is the whole point:
/// `claim_scope` claims parent-observed execution only for parent-executed
/// code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SubEffectPoint {
    /// A commit-tree child has exited with its object written; the coordinator
    /// has not read or recorded the printed id. R27 residue.
    IdUnread,
    /// Bytes written, possibly partially, not yet synced.
    ///
    /// In kill mode this is the whole of what the packet tables for a written
    /// append — "torn: truncated on the next open, previous prefix;
    /// complete-unsynced: either prefix". In error-return mode it is the
    /// *first* of three separately required cases: the partial write that
    /// returned `Err` before a newline was committed.
    Written,
    /// The complete newline-terminated line is written and the flush has not
    /// run.
    ///
    /// The second required error-return case
    /// (`fault_injection_registry.structure`: "error-return entries for
    /// Written-partial-then-Err, **Written-full-then-flush-Err**, and
    /// Synced-Err"). A separate point rather than a second entry at
    /// `Written/ErrorReturn`, because that key is one key: the registry is
    /// keyed by site x phase x order x mode, so two cases at one coordinate
    /// are a duplicate the format refuses, and one of the two would go
    /// unexecuted while the coordinate read as complete. The durable shapes
    /// differ too — a partial line is a torn tail the next open truncates, a
    /// complete unsynced line is a prefix the barrier makes durable — so they
    /// are two rows, not one row observed twice.
    ///
    /// Kill mode is deliberately absent: `structure` tables kill entries for
    /// `Written` and `Synced` only, and a kill here leaves the
    /// complete-unsynced prefix `Written`'s kill entry already covers.
    /// Declaring one would manufacture a coverage obligation the design does
    /// not make.
    WrittenFull,
    /// The append is synced.
    Synced,
    /// The log file was created (and its directory fsynced) because it was
    /// absent.
    Create,
    /// An unterminated final line was truncated before the append handle was
    /// taken.
    TruncateTornTail,
    /// The complete surviving prefix was synced — the durable half of the
    /// stable-prefix barrier.
    SyncPrefix,
    /// Windows: the coordinator process joined the ambient job at startup.
    AmbientJobJoined,
    /// Windows: the child was created suspended, already an ambient-job member.
    CreatedSuspended,
    /// Windows: the child was assigned to its private job object.
    PrivateJobAssigned,
    /// Windows: the suspended child was resumed.
    Resumed,
    /// Unix: the per-invocation reaper was forked and took its cleanup hold.
    ReaperStarted,
    /// Unix: in the forked child, before `exec`, the pgid was set and the group
    /// registered.
    PreExecPgidAndRegister,
    /// Unix: the child `exec`ed.
    Exec,
    /// Unix: the parent registered the running group.
    Registered,
}

impl SubEffectPoint {
    /// Every point.
    pub const ALL: &'static [Self] = &[
        Self::IdUnread,
        Self::Written,
        Self::WrittenFull,
        Self::Synced,
        Self::Create,
        Self::TruncateTornTail,
        Self::SyncPrefix,
        Self::AmbientJobJoined,
        Self::CreatedSuspended,
        Self::PrivateJobAssigned,
        Self::Resumed,
        Self::ReaperStarted,
        Self::PreExecPgidAndRegister,
        Self::Exec,
        Self::Registered,
    ];

    /// The point's name inside its site.
    pub const fn name(self) -> &'static str {
        match self {
            Self::IdUnread => "IdUnread",
            Self::Written => "Written",
            Self::WrittenFull => "WrittenFull",
            Self::Synced => "Synced",
            Self::Create => "Create",
            Self::TruncateTornTail => "TruncateTornTail",
            Self::SyncPrefix => "SyncPrefix",
            Self::AmbientJobJoined => "AmbientJobJoined",
            Self::CreatedSuspended => "CreatedSuspended",
            Self::PrivateJobAssigned => "PrivateJobAssigned",
            Self::Resumed => "Resumed",
            Self::ReaperStarted => "ReaperStarted",
            Self::PreExecPgidAndRegister => "PreExecPgidAndRegister",
            Self::Exec => "Exec",
            Self::Registered => "Registered",
        }
    }

    /// The injection modes this point supports.
    ///
    /// Kill is all but universal: a coordinator can die anywhere, and
    /// [`Self::WrittenFull`] is the one point that does not declare it — for
    /// the reason its own documentation gives, that a kill there leaves the
    /// complete-unsynced prefix [`Self::Written`]'s kill entry already covers,
    /// so declaring the mode would manufacture a coverage obligation
    /// `structure` does not table. Error-return is
    /// narrower — it exists where the design gives the funnel an error contract
    /// to return *through*. The Event points all have one (the append-error
    /// protocol, and `SyncPrefix`'s resumable refusal), and Windows'
    /// `AmbientJobJoined` has one ("failure refuses the write command").
    /// [`Self::IdUnread`] has none: the packet describes it only as a durable
    /// prefix a kill leaves, and inventing an error contract for it would be
    /// inventing a resume action nothing tables.
    pub const fn modes(self) -> &'static [InjectionMode] {
        match self {
            Self::Written
            | Self::Synced
            | Self::Create
            | Self::TruncateTornTail
            | Self::SyncPrefix
            | Self::AmbientJobJoined => InjectionMode::ALL,
            Self::WrittenFull => &[InjectionMode::ErrorReturn],
            Self::IdUnread
            | Self::CreatedSuspended
            | Self::PrivateJobAssigned
            | Self::Resumed
            | Self::ReaperStarted
            | Self::PreExecPgidAndRegister
            | Self::Exec
            | Self::Registered => &[InjectionMode::Kill],
        }
    }

    /// The platform this point exists on.
    ///
    /// A property of the point and not of a machine, which is why the answer is
    /// a [`Platform`] and not a [`Host`]: [`Platform::Any`] is "exists wherever
    /// the parent runs", and no host has that value. [`Platform::required_on`]
    /// is what turns this into a requirement on a given host.
    pub const fn platform(self) -> Platform {
        match self {
            Self::AmbientJobJoined
            | Self::CreatedSuspended
            | Self::PrivateJobAssigned
            | Self::Resumed => Platform::Windows,
            Self::ReaperStarted | Self::PreExecPgidAndRegister | Self::Exec | Self::Registered => {
                Platform::Unix
            }
            Self::IdUnread
            | Self::Written
            | Self::WrittenFull
            | Self::Synced
            | Self::Create
            | Self::TruncateTornTail
            | Self::SyncPrefix => Platform::Any,
        }
    }

    /// Whether this point supports `mode`.
    pub fn supports(self, mode: InjectionMode) -> bool {
        self.modes().contains(&mode)
    }
}

impl fmt::Display for SubEffectPoint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    // -----------------------------------------------------------------------
    // The canonical spellings
    // -----------------------------------------------------------------------

    #[test]
    fn every_funnel_group_spells_the_name_a_dotted_site_name_is_built_from() {
        // `EffectSiteId::name` is `format!("{}.{}", group().name(), variant())`,
        // so the sibling suite's "a site's name starts with its group's name"
        // is both sides of one expression and cannot fail. These are the
        // literals, written here and not read back from `name()`.
        let expected = [
            (FunnelGroup::Worktree, "Worktree"),
            (FunnelGroup::Snapshot, "Snapshot"),
            (FunnelGroup::Ref, "Ref"),
            (FunnelGroup::Object, "Object"),
            (FunnelGroup::RunDir, "RunDir"),
            (FunnelGroup::Event, "Event"),
            (FunnelGroup::Answer, "Answer"),
            (FunnelGroup::Lock, "Lock"),
            (FunnelGroup::Report, "Report"),
            (FunnelGroup::Process, "Process"),
            (FunnelGroup::Container, "Container"),
        ];
        assert_eq!(expected.len(), FunnelGroup::ALL.len());
        for (group, name) in expected {
            assert_eq!(group.name(), name);
            assert_eq!(group.to_string(), name, "Display is not `name()`");
        }
        let names: BTreeSet<&str> = FunnelGroup::ALL.iter().map(|g| g.name()).collect();
        assert_eq!(
            names.len(),
            FunnelGroup::ALL.len(),
            "two groups share a name"
        );
    }

    #[test]
    fn every_resource_row_spells_its_ledger_id() {
        // `name()` is documented as "the row's ledger id" and reaches the
        // outside world only through `Display`; nothing else in the crate reads
        // it, so without this table a mutation of either is silent.
        let expected = [
            (ResourceRow::R9, "R9"),
            (ResourceRow::R10, "R10"),
            (ResourceRow::R11, "R11"),
            (ResourceRow::R12, "R12"),
            (ResourceRow::R17, "R17"),
            (ResourceRow::R18, "R18"),
            (ResourceRow::R19, "R19"),
            (ResourceRow::R21, "R21"),
            (ResourceRow::R22, "R22"),
            (ResourceRow::R23, "R23"),
            (ResourceRow::R24, "R24"),
            (ResourceRow::R25, "R25"),
            (ResourceRow::R26, "R26"),
            (ResourceRow::R27, "R27"),
            (ResourceRow::R28, "R28"),
        ];
        assert_eq!(expected.len(), ResourceRow::ALL.len());
        for (row, name) in expected {
            assert_eq!(row.name(), name);
            assert_eq!(row.to_string(), name, "Display is not `name()`");
        }
        let names: BTreeSet<&str> = ResourceRow::ALL.iter().map(|r| r.name()).collect();
        assert_eq!(names.len(), ResourceRow::ALL.len(), "two rows share an id");
    }

    #[test]
    fn no_row_of_the_logical_domain_and_not_operator_owned_r20_is_a_variant() {
        // The enum's two exclusion rules, stated as the numbers they exclude:
        // R1-R8 and R13-R16 are the logical fold/broker domain, and R20 is
        // external-physical but `operator_owned` -- "never created or pruned by
        // a run". Absent numbers rather than absent variants, because the
        // defect this catches is a row admitted later without either rule being
        // revisited.
        let admitted: BTreeSet<&str> = ResourceRow::ALL.iter().map(|r| r.name()).collect();
        for n in 1..=28u8 {
            let id = format!("R{n}");
            let expected = !matches!(n, 1..=8 | 13..=16 | 20);
            assert_eq!(
                admitted.contains(id.as_str()),
                expected,
                "{id} is on the wrong side of the two exclusion rules"
            );
        }
        assert_eq!(admitted.len(), 15);
    }

    #[test]
    fn every_enforcement_domain_is_the_one_its_rows_belong_to() {
        for row in ResourceRow::ALL {
            let process_local =
                matches!(row, ResourceRow::R17 | ResourceRow::R22 | ResourceRow::R28);
            assert_eq!(
                row.domain(),
                if process_local {
                    EnforcementDomain::ProcessLocalOs
                } else {
                    EnforcementDomain::ExternalPhysical
                },
                "{row}"
            );
        }
        // Both domains are populated, so the crossing above is not a constant.
        let domains: BTreeSet<EnforcementDomain> =
            ResourceRow::ALL.iter().map(|r| r.domain()).collect();
        assert_eq!(domains.len(), 2);
    }

    #[test]
    fn every_sub_effect_point_spells_its_own_name() {
        let expected = [
            (SubEffectPoint::IdUnread, "IdUnread"),
            (SubEffectPoint::Written, "Written"),
            (SubEffectPoint::WrittenFull, "WrittenFull"),
            (SubEffectPoint::Synced, "Synced"),
            (SubEffectPoint::Create, "Create"),
            (SubEffectPoint::TruncateTornTail, "TruncateTornTail"),
            (SubEffectPoint::SyncPrefix, "SyncPrefix"),
            (SubEffectPoint::AmbientJobJoined, "AmbientJobJoined"),
            (SubEffectPoint::CreatedSuspended, "CreatedSuspended"),
            (SubEffectPoint::PrivateJobAssigned, "PrivateJobAssigned"),
            (SubEffectPoint::Resumed, "Resumed"),
            (SubEffectPoint::ReaperStarted, "ReaperStarted"),
            (
                SubEffectPoint::PreExecPgidAndRegister,
                "PreExecPgidAndRegister",
            ),
            (SubEffectPoint::Exec, "Exec"),
            (SubEffectPoint::Registered, "Registered"),
        ];
        assert_eq!(expected.len(), SubEffectPoint::ALL.len());
        for (point, name) in expected {
            assert_eq!(point.name(), name);
            assert_eq!(point.to_string(), name, "Display is not `name()`");
        }
        let names: BTreeSet<&str> = SubEffectPoint::ALL.iter().map(|p| p.name()).collect();
        assert_eq!(
            names.len(),
            SubEffectPoint::ALL.len(),
            "two points share a name"
        );
    }

    #[test]
    fn every_durable_event_displays_the_tag_the_log_writes() {
        // `kind()` is crossed against `TOPOLOGY_EVENT_KINDS` by the sibling
        // suite; what nothing crossed is `Display`, which is what a diagnostic
        // quoting an adjacency prints.
        for kind in DurableEvent::ALL {
            assert_eq!(kind.to_string(), kind.kind(), "{kind:?}");
        }
        let tags: BTreeSet<&str> = DurableEvent::ALL.iter().map(|k| k.kind()).collect();
        assert_eq!(tags.len(), DurableEvent::ALL.len(), "two kinds share a tag");
        assert_eq!(DurableEvent::RunStarted.kind(), "run_started");
        assert_eq!(
            DurableEvent::MergeVerificationUnavailable.kind(),
            "merge_verification_unavailable"
        );
    }

    #[test]
    fn every_fault_row_displays_the_id_the_matrix_writes() {
        for row in FaultRow::ALL {
            assert_eq!(row.to_string(), row.id(), "{row:?}");
            assert!(
                row.id().starts_with("T-") && row.id().to_uppercase() == row.id(),
                "{row:?} is not spelled the way the matrix spells a row"
            );
        }
        let ids: BTreeSet<&str> = FaultRow::ALL.iter().map(|r| r.id()).collect();
        assert_eq!(ids.len(), FaultRow::ALL.len(), "two rows share an id");
        assert_eq!(FaultRow::TCandObj.id(), "T-CAND-OBJ");
        assert_eq!(FaultRow::TRepairDispatch.id(), "T-REPAIR-DISPATCH");
    }

    // -----------------------------------------------------------------------
    // The small closed answers
    // -----------------------------------------------------------------------

    #[test]
    fn the_two_claimed_scopes_are_topology_and_shared_and_legacy_is_not_one() {
        assert!(SiteScope::Topology.is_claimed());
        assert!(SiteScope::Shared.is_claimed());
        assert!(
            !SiteScope::Legacy.is_claimed(),
            "a legacy site would acquire the ST-07 bijection requirement"
        );
    }

    #[test]
    fn an_injection_mode_is_a_kill_or_an_error_return_and_all_lists_both() {
        assert_eq!(
            InjectionMode::ALL,
            &[InjectionMode::Kill, InjectionMode::ErrorReturn]
        );
    }

    #[test]
    fn each_host_names_itself_requires_its_own_platform_and_is_the_others_other() {
        let expected = [
            (Host::Windows, "windows", Platform::Windows),
            (Host::Unix, "unix", Platform::Unix),
        ];
        assert_eq!(expected.len(), Host::ALL.len());
        for (host, name, platform) in expected {
            assert_eq!(host.name(), name);
            assert_eq!(host.to_string(), name, "Display is not `name()`");
            assert_eq!(host.platform(), platform);
            // Written as a fixed pair rather than `current().other()`, which is
            // reflexive and holds for an `other` that returns its argument.
            assert_ne!(host.other(), host, "{name} is its own other host");
            assert_eq!(host.other().other(), host, "{name}");
        }
        assert_eq!(Host::Windows.other(), Host::Unix);
        assert_eq!(Host::Unix.other(), Host::Windows);
        assert_eq!(
            Host::current(),
            if cfg!(windows) {
                Host::Windows
            } else {
                Host::Unix
            }
        );
    }

    #[test]
    fn a_point_is_required_on_a_host_exactly_when_the_platforms_agree_or_it_is_any() {
        for platform in [Platform::Any, Platform::Windows, Platform::Unix] {
            for host in Host::ALL.iter().copied() {
                let expected = platform == Platform::Any || platform == host.platform();
                assert_eq!(
                    platform.required_on(host),
                    expected,
                    "{platform:?} on {host}"
                );
            }
        }
        // Every point is required somewhere: a point required on no host is a
        // point no suite has to execute, which is the shape of the false
        // success `Host` exists to have made impossible.
        for point in SubEffectPoint::ALL {
            assert!(
                Host::ALL
                    .iter()
                    .any(|host| point.platform().required_on(*host)),
                "{point} is required on no host"
            );
        }
    }

    #[test]
    fn kill_is_declared_everywhere_except_written_full_and_error_return_where_a_contract_exists() {
        for point in SubEffectPoint::ALL {
            assert_eq!(
                point.supports(InjectionMode::Kill),
                *point != SubEffectPoint::WrittenFull,
                "{point}: the doc's exception is exactly WrittenFull"
            );
            assert_eq!(
                point.supports(InjectionMode::ErrorReturn),
                point.modes().contains(&InjectionMode::ErrorReturn),
                "{point}"
            );
            assert!(!point.modes().is_empty(), "{point} supports no mode at all");
        }
        assert_eq!(
            SubEffectPoint::WrittenFull.modes(),
            &[InjectionMode::ErrorReturn]
        );
        assert_eq!(SubEffectPoint::IdUnread.modes(), &[InjectionMode::Kill]);
    }

    #[test]
    fn an_adjacency_carries_its_event_and_none_carries_nothing() {
        for kind in DurableEvent::ALL {
            assert_eq!(Adjacent::Before(*kind).event(), Some(*kind));
            assert_eq!(Adjacent::After(*kind).event(), Some(*kind));
        }
        assert_eq!(Adjacent::None.event(), None);
    }

    // -----------------------------------------------------------------------
    // The wire forms
    // -----------------------------------------------------------------------

    /// serde's `rename_all = "snake_case"`, reimplemented so the test can say
    /// what the rule is rather than restate its output variant by variant.
    fn snake_case(identifier: &str) -> String {
        let mut out = String::new();
        for (index, ch) in identifier.char_indices() {
            if ch.is_ascii_uppercase() {
                if index != 0 {
                    out.push('_');
                }
                out.push(ch.to_ascii_lowercase());
            } else {
                out.push(ch);
            }
        }
        out
    }

    #[test]
    fn the_snake_case_rule_is_the_one_serde_applies() {
        assert_eq!(snake_case("R9"), "r9");
        assert_eq!(snake_case("R10"), "r10");
        assert_eq!(snake_case("TCandObj"), "t_cand_obj");
        assert_eq!(
            snake_case("PreExecPgidAndRegister"),
            "pre_exec_pgid_and_register"
        );
        assert_eq!(snake_case("Any"), "any");
    }

    fn wire_form<T: serde::Serialize>(value: &T) -> String {
        let json = serde_json::to_string(value).expect("a vocabulary value serializes");
        json.trim_matches('"').to_owned()
    }

    #[test]
    fn every_vocabulary_value_writes_the_snake_case_of_its_variant() {
        // The wire form of `effect_sites.json` and of the checked-in
        // `effects/residue-classes.json` `row` column. Pinned as the rule plus
        // the awkward outputs, because the rule is what a later `rename_all`
        // edit would break.
        for group in FunnelGroup::ALL {
            assert_eq!(wire_form(group), snake_case(&format!("{group:?}")));
        }
        for row in ResourceRow::ALL {
            assert_eq!(wire_form(row), snake_case(&format!("{row:?}")));
        }
        for row in FaultRow::ALL {
            assert_eq!(wire_form(row), snake_case(&format!("{row:?}")));
        }
        for point in SubEffectPoint::ALL {
            assert_eq!(wire_form(point), snake_case(&format!("{point:?}")));
        }
        for host in Host::ALL {
            assert_eq!(wire_form(host), snake_case(&format!("{host:?}")));
        }
        assert_eq!(wire_form(&FunnelGroup::RunDir), "run_dir");
        assert_eq!(wire_form(&ResourceRow::R9), "r9");
        assert_eq!(wire_form(&FaultRow::TCandObj), "t_cand_obj");
        assert_eq!(wire_form(&SubEffectPoint::WrittenFull), "written_full");
        assert_eq!(
            wire_form(&EnforcementDomain::ProcessLocalOs),
            "process_local_os"
        );
        assert_eq!(wire_form(&Platform::Any), "any");
        assert_eq!(wire_form(&SiteScope::Legacy), "legacy");
        assert_eq!(wire_form(&InjectionMode::ErrorReturn), "error_return");
    }

    #[test]
    fn the_wire_form_is_not_the_ledger_id_for_the_four_types_that_have_one() {
        // Recorded rather than repaired. `effects/residue-classes.json` is
        // compared byte-for-byte by `effects::tests`, and its `row` column is
        // this form, so unifying the two spellings regenerates a checked-in
        // allowlist and is outside one file's sweep. The finding is
        // `SWEEP-VOCAB-001`; this assertion is what makes the divergence a
        // pinned fact rather than an accident, and it is the assertion that
        // fails when the finding is taken up.
        assert_ne!(wire_form(&FunnelGroup::RunDir), FunnelGroup::RunDir.name());
        assert_ne!(wire_form(&ResourceRow::R9), ResourceRow::R9.name());
        assert_ne!(wire_form(&FaultRow::TCandObj), FaultRow::TCandObj.id());
        assert_ne!(
            wire_form(&SubEffectPoint::IdUnread),
            SubEffectPoint::IdUnread.name()
        );
        // `DurableEvent` and `Host` are the two whose accessor and wire form do
        // agree, which is why the divergence above reads as drift and not as a
        // convention.
        for kind in DurableEvent::ALL {
            assert_eq!(wire_form(kind), kind.kind(), "{kind}");
        }
        for host in Host::ALL {
            assert_eq!(wire_form(host), host.name(), "{host}");
        }
    }

    #[test]
    fn an_adjacency_round_trips_and_refuses_a_second_key_or_an_unknown_one() {
        let before = Adjacent::Before(DurableEvent::RunStarted);
        let after = Adjacent::After(DurableEvent::RunStarted);
        assert_eq!(
            serde_json::to_string(&before).expect("serializes"),
            r#"{"before":"run_started"}"#
        );
        assert_eq!(
            serde_json::to_string(&after).expect("serializes"),
            r#"{"after":"run_started"}"#
        );
        assert_eq!(
            serde_json::to_string(&Adjacent::None).expect("serializes"),
            r#""none""#
        );
        for (text, value) in [
            (r#"{"before":"run_started"}"#, before),
            (r#"{"after":"run_started"}"#, after),
            (r#""none""#, Adjacent::None),
        ] {
            assert_eq!(
                serde_json::from_str::<Adjacent>(text).expect("round trips"),
                value
            );
        }
        // What actually protects the form: an externally tagged enum admits one
        // key, and only a declared one. Both refusals are the enum
        // representation's, not `deny_unknown_fields`', which has no field to
        // deny on a newtype or unit variant.
        for refused in [
            r#"{"before":"run_started","after":"run_started"}"#,
            r#"{"before":"run_started","extra":1}"#,
            r#"{"during":"run_started"}"#,
            r#"{"before":"never_appended"}"#,
            r#""nothing""#,
        ] {
            assert!(
                serde_json::from_str::<Adjacent>(refused).is_err(),
                "{refused} was accepted"
            );
        }
    }

    // -----------------------------------------------------------------------
    // The census: every `ALL` lists every variant of its enum
    // -----------------------------------------------------------------------
    //
    // Each `ALL` is a hand-written list beside a hand-written enum, and it is
    // load-bearing: `SubEffectPoint::ALL` is the coverage obligation the
    // bijection check enforces, `ResourceRow::ALL` the domain of "every row has
    // a claimed site", `Host::ALL` the reason a platform claim is not vacuous
    // on the other host. A variant added to an enum and not to its `ALL` is
    // silent -- the sibling suite's `assert_eq!(ALL.len(), 11)` compares two
    // numbers that move together. This census reads the source and compares the
    // enum's variants to its `ALL`.

    /// Replace every comment and every string, byte-string, raw-string and
    /// character literal with spaces, preserving byte length and newlines.
    fn blank_comments_and_literals(source: &str) -> String {
        let bytes = source.as_bytes();
        let mut out = bytes.to_vec();
        let at = |i: usize| bytes.get(i).copied();
        let ident_byte =
            |b: Option<u8>| matches!(b, Some(c) if c.is_ascii_alphanumeric() || c == b'_');
        let blank = |out: &mut Vec<u8>, from: usize, to: usize| {
            for slot in out.iter_mut().take(to).skip(from) {
                if *slot != b'\n' {
                    *slot = b' ';
                }
            }
        };
        let mut i = 0;
        while i < bytes.len() {
            match (at(i), at(i + 1)) {
                (Some(b'/'), Some(b'/')) => {
                    let end = source
                        .get(i..)
                        .and_then(|rest| rest.find('\n'))
                        .map_or(bytes.len(), |offset| i + offset);
                    blank(&mut out, i, end);
                    i = end;
                }
                (Some(b'/'), Some(b'*')) => {
                    let mut depth = 1usize;
                    let mut j = i + 2;
                    while j < bytes.len() && depth > 0 {
                        match (at(j), at(j + 1)) {
                            (Some(b'/'), Some(b'*')) => {
                                depth += 1;
                                j += 2;
                            }
                            (Some(b'*'), Some(b'/')) => {
                                depth -= 1;
                                j += 2;
                            }
                            _ => j += 1,
                        }
                    }
                    blank(&mut out, i, j);
                    i = j;
                }
                (Some(first), _)
                    if (first == b'r' || first == b'b') && !ident_byte(at(i.wrapping_sub(1))) =>
                {
                    // `r"`, `r#"`, `b"`, `br"`, `br#"` -- and anything else
                    // starting with these letters is an identifier.
                    let mut j = i + 1;
                    if first == b'b' && at(j) == Some(b'r') {
                        j += 1;
                    }
                    let raw = first == b'r' || at(i + 1) == Some(b'r');
                    let mut hashes = 0usize;
                    if raw {
                        while at(j) == Some(b'#') {
                            hashes += 1;
                            j += 1;
                        }
                    }
                    if at(j) != Some(b'"') || (!raw && hashes > 0) {
                        i += 1;
                        continue;
                    }
                    j += 1;
                    let end = if raw {
                        let mut k = j;
                        loop {
                            if k >= bytes.len() {
                                break bytes.len();
                            }
                            if at(k) == Some(b'"')
                                && (0..hashes).all(|h| at(k + 1 + h) == Some(b'#'))
                            {
                                break k + 1 + hashes;
                            }
                            k += 1;
                        }
                    } else {
                        end_of_quoted(bytes, j)
                    };
                    blank(&mut out, i, end);
                    i = end;
                }
                (Some(b'"'), _) => {
                    let end = end_of_quoted(bytes, i + 1);
                    blank(&mut out, i, end);
                    i = end;
                }
                (Some(b'\''), _) => {
                    // A lifetime, not a literal, unless the quote closes within
                    // one escape or one character. `&'static [Self]` is the
                    // shape that a naive scan swallows the rest of the file on.
                    let end = if at(i + 1) == Some(b'\\') {
                        let mut k = i + 2;
                        while k < bytes.len() && at(k) != Some(b'\'') {
                            k += 1;
                        }
                        Some(k + 1)
                    } else if at(i + 2) == Some(b'\'') {
                        Some(i + 3)
                    } else {
                        None
                    };
                    match end {
                        Some(end) => {
                            blank(&mut out, i, end);
                            i = end;
                        }
                        None => i += 1,
                    }
                }
                _ => i += 1,
            }
        }
        String::from_utf8(out).unwrap_or_else(|_| source.to_owned())
    }

    /// The index one past the closing quote of a `"`-delimited literal whose
    /// body starts at `from`.
    fn end_of_quoted(bytes: &[u8], from: usize) -> usize {
        let mut i = from;
        while i < bytes.len() {
            match bytes.get(i).copied() {
                Some(b'\\') => i += 2,
                Some(b'"') => return i + 1,
                Some(_) => i += 1,
                None => break,
            }
        }
        bytes.len()
    }

    /// `(enum name, variants declared)` for every `pub enum` in `source`.
    fn declared_variants(source: &str) -> Vec<(String, usize)> {
        let blanked = blank_comments_and_literals(source);
        let lines: Vec<&str> = blanked.lines().collect();
        let mut found = Vec::new();
        let mut index = 0usize;
        while let Some(line) = lines.get(index) {
            index += 1;
            let Some(name) = line
                .strip_prefix("pub enum ")
                .and_then(|rest| rest.strip_suffix(" {"))
            else {
                continue;
            };
            let mut variants = 0usize;
            while let Some(body) = lines.get(index) {
                index += 1;
                if *body == "}" {
                    break;
                }
                if is_variant_line(body.trim()) {
                    variants += 1;
                }
            }
            found.push((name.to_owned(), variants));
        }
        found
    }

    fn is_variant_line(text: &str) -> bool {
        let Some(body) = text.strip_suffix(',') else {
            return false;
        };
        let identifier = match body.find('(') {
            Some(open) if body.ends_with(')') => body.get(..open).unwrap_or_default(),
            Some(_) => return false,
            None => body,
        };
        let mut characters = identifier.chars();
        matches!(characters.next(), Some(first) if first.is_ascii_uppercase())
            && characters.all(|c| c.is_ascii_alphanumeric())
    }

    #[test]
    fn the_census_reads_variants_and_not_the_text_that_looks_like_them() {
        // The blanker's positive control: a variant named only inside a comment
        // or a string literal is not a variant, and a `'static` lifetime does
        // not swallow the file behind it.
        let fixture = "\
const NOISE: &'static str = \"pub enum Ghost {\\n    Boo,\\n}\";
const RAW: &str = r#\"pub enum Phantom {\"#;
pub enum Real {
    One,
    // Two,
    Three(Payload),
}
";
        assert_eq!(
            blank_comments_and_literals(fixture).len(),
            fixture.len(),
            "the blanker moved a byte"
        );
        assert_eq!(
            declared_variants(fixture),
            vec![("Real".to_owned(), 2)],
            "a commented-out or quoted variant was counted, or a real one was not"
        );

        // The injected violation: one variant added to the enum and to nothing
        // else has to move the count.
        let widened = fixture.replace("    Three(Payload),", "    Three(Payload),\n    Four,");
        assert_eq!(declared_variants(&widened), vec![("Real".to_owned(), 3)]);

        // And the blanker survives the two literal shapes that make a naive
        // scanner lose its place.
        let tricky = "let comma = ',';\nlet quote = '\\'';\npub enum After {\n    One,\n}\n";
        assert_eq!(declared_variants(tricky), vec![("After".to_owned(), 1)]);
    }

    #[test]
    fn every_all_lists_every_variant_of_its_enum() {
        let counted = declared_variants(include_str!("vocab.rs"));
        let names: Vec<&str> = counted.iter().map(|(name, _)| name.as_str()).collect();
        // The domain this census claims: the eleven `pub enum`s of this file,
        // by name. A twelfth, or a rename, fails here rather than going
        // uncounted.
        assert_eq!(
            names,
            vec![
                "FunnelGroup",
                "ResourceRow",
                "EnforcementDomain",
                "DurableEvent",
                "Adjacent",
                "FaultRow",
                "SiteScope",
                "InjectionMode",
                "Platform",
                "Host",
                "SubEffectPoint",
            ],
            "the enums of this file are not the ones the census expects"
        );

        let expected: &[(&str, usize)] = &[
            ("FunnelGroup", FunnelGroup::ALL.len()),
            ("ResourceRow", ResourceRow::ALL.len()),
            // No `ALL`: the count is the literal the type's documentation says.
            ("EnforcementDomain", 2),
            ("DurableEvent", DurableEvent::ALL.len()),
            ("Adjacent", 3),
            ("FaultRow", FaultRow::ALL.len()),
            ("SiteScope", 3),
            ("InjectionMode", InjectionMode::ALL.len()),
            ("Platform", 3),
            ("Host", Host::ALL.len()),
            ("SubEffectPoint", SubEffectPoint::ALL.len()),
        ];
        for (name, declared) in &counted {
            let expected = expected
                .iter()
                .find(|(candidate, _)| candidate == name)
                .map(|(_, count)| *count)
                .unwrap_or_default();
            assert_eq!(
                *declared, expected,
                "`{name}` declares {declared} variants and its list has {expected}"
            );
        }
        // Non-zero, so a scanner that found nothing cannot pass by finding
        // nothing on both sides.
        assert!(counted.iter().all(|(_, declared)| *declared > 0));
    }
}
